#!/bin/python3
import sys
from colorama import Fore

def displayFile(): 
    try: 
        for i, eachFile in enumerate(sys.argv[1:]): 
                if eachFile != '-h': 
                    fhandler = open(eachFile); 
                    print("### [", i, "] File Name: ", eachFile, " ###", sep=''); 
                    for i, eachLine in enumerate(fhandler, start=1):
                        print(i, eachLine, end="");
                else: 
                    help();
                print("");
    except:
        print(Fore.RED + "[Err]: Unexpected Error Occurred !");
        quit(); 


def help():  # COMPLETED: create a help menu with explaination. 
    mess = """Usage: lcat <options> <fileName> 
lcat is a small program used to concatinate lines using with
line numbers. The program is written in Python3. 

Options: 
    -h -> help menu. 

Example: 
    lcat test.txt

Output: 
    1 foo
    2 bar
    3 foo
    """
    print(mess);


displayFile();
    
